swagger: '2.0'
info:
  description: API responsible for mananging Users and their Games
  version: 1.0.0
  title: Queens Gambit API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8080
basePath: /queens-gambit-api/v1
tags:
  - name: User
    description: Operations regarding the users
  - name: Game
    description: Operations regarding the games
schemes:
  - http
paths:
  /games:
    get:
      tags:
        - Game
      summary: Gets data from all Games
      operationId: getGames
      produces:
        - "application/json"
      responses:
        '200':
          description: "Game data suscessfully retrieved"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/GameResponse"
        '500':
          description: "Internal error ocurred while getting Game data"
        '400':
          description: "Invalid Request"
        '404':
          description: "No Games found"

  /users:
    get:
      tags:
        - User
      summary: Gets data from all Users
      operationId: getUsers
      produces:
        - "application/json"
      responses:
        '200':
          description: "User data suscessfully retrieved"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UserResponse"
        '500':
          description: "Internal error ocurred while getting User data"
        '400':
          description: "Invalid Request"
        '404':
          description: "No Users found"

definitions:
  GameResponse:
    type: object
    properties:
      full_name:
        type: string
        description: Full name of the game
      launch_year:
        type: integer
        format: int64
        description: Launch year
      developer:
        type: string
        format: int64
        description: Developer of the game
      players:
        type: array
        description: List of players
        items:
          $ref: '#/definitions/UserReducedResponse'
      owners:
        type: array
        description: List of owners
        items:
          $ref: '#/definitions/UserReducedResponse'

  UserResponse:
    type: object
    properties:
      login:
        type: string
        description: User login
        minLength: 1
      full_name:
        type: string
        format: int64
        description: Full name of the User
      city_name:
        type: string
        description: Ip Address of the Machine
      age:
        type: integer
        format: int64
        description: User age
      user_wanted_games:
        type: array
        description: List of wanted games
        items:
          $ref: '#/definitions/ReducedGameResponse'
      user_owned_games:
        type: array
        description: List of owned games
        items:
          $ref: '#/definitions/ReducedGameResponse'

  UserReducedResponse:
    type: object
    properties:
      full_name:
        type: string
        description: name of the player
      login:
        type: string
        description: login of the player

  ReducedGameResponse:
    type: object
    properties:
      full_name:
        type: string
        description: Full name of the game